markdown: rdiscount
permalink: /:title/
url: http://lamborryan.github.io
highlighter: pygments
gems:
    - jekyll-paginate

paginate: 5
paginate_path: "/page/:num"

name: 追风的蓝宝
description: 追风的蓝宝 | keep learning.
author: 追风的蓝宝
email: lamborryan@gmail.com
duoshuo: lamborryan
hub:
safe: false
paginate: 100
github: lamborryan
about: "菜鸟一枚。"
